export {NavigatePage} from './navigate'
export {default as LoginPage} from './login'
export {default as RegistrationPage} from './registration'
export {MessengerPage} from './messenger'
export {ProfilePage} from './profile'
export {ErrorPage} from './404'
export {ErrorFixingPage} from './500'
export {ModalsPage} from './modals'
